version: '3.4'
services:
  ${project.artifactId}-share:
    image: alfresco-share-${project.artifactId}:development
    build:
      dockerfile: ./Dockerfile
      context: ${project.basedir}/${project.artifactId}-share-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: ${project.artifactId}-acs
      REPO_PORT: 8080
    ports:
      - "${share.port}:8080"
      - "${share.debug.port}:8888"
  ${project.artifactId}-acs:
    image: alfresco-content-services-${project.artifactId}:development
    build:
      dockerfile: ./Dockerfile
      context: ${project.basedir}/${project.artifactId}-platform-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - ${project.artifactId}-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - ${project.artifactId}-postgres
volumes:
  ${project.artifactId}-acs-volume:
